name: Release to terraform public registry

on:
  push:
    tags:
      - '*'
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          name: "v${{ github.ref_name }}"